spring.application.name=springapp

# MySQL configuration
spring.datasource.url=jdbc:mysql://localhost:3306/9c586973_fafe_4b5e_85c6_cc88f48e915a?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# SpringDoc / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# React Integration
server.port=8091
